smurfelite/games/urls.py
from django.urls import path

from . import views


urlpatterns = [

]

smurfelite/smurfelite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("users.urls")),
    path('', include("orders.urls")),
    path('games/', include("games.urls")),
]

smurfelite/users/urls.py
from django.urls import path

from . import views
app_name = 'user'

urlpatterns = [
    path("login/", views.user_login, name="login"),
    path('logout/', views.logout_user, name='logout'),
    path("register/", views.user_register, name="register"),
    path("profile/", views.profile, name="profile"),
]

smurfelite/users/models.py
from uuid import uuid4

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    email = models.EmailField(_("Email Address"), unique=True)


class Profile(models.Model):
    user = models.OneToOneField(User, related_name="profile", on_delete=models.CASCADE)
    first_name = models.CharField(max_length=200, verbose_name="First Name")
    last_name = models.CharField(max_length=200, verbose_name="Last Name")
    username = models.CharField(max_length=150, unique=True)
    email = models.EmailField(unique=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    id = models.UUIDField(default=uuid4, primary_key=True, editable=False)

    def __str__(self):
        return self.username

smurfelite/users/forms.py
from django import forms

from .models import Profile


class RegisterForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control form-control-lg",
                "placeholder": "Enter username",
            }
        )
    )
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                "class": "form-control form-control-lg",
                "placeholder": "Enter Email Address",
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control form-control-lg",
                "placeholder": "Enter Password",
            }
        )
    )
    password_repeat = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control form-control-lg",
                "placeholder": "Confirm Password",
            }
        )
    )


class ProfileForm(forms.ModelForm):
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Enter First Name"})
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Enter Last Name"})
    )

    class Meta:
        model = Profile
        exclude = ("user", "id")
        widgets = {
            "username": forms.TextInput(attrs={"placeholder": "Enter a username"}),
            "email": forms.EmailInput(attrs={"placeholder": "Enter an Email Id"}),
        }

smurfelite/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout, login, authenticate

from .models import User
from .forms import RegisterForm


def user_login(request):

    if not request.user.is_authenticated:
        # if this is a POST request we need to process the form data
        template = "users/login.html"

        if request.method == "POST":
            # Process the request if posted data are available
            username = request.POST.get('username')
            password = request.POST.get('password')
            # Check username and password combination if correct
            user = authenticate(username=username, password=password)

            if user is not None:
                # Save session as cookie to login the user
                login(request, user)
                # Success, now let's login the user.
                return redirect("user:profile")
            else:
                # Incorrect credentials, let's throw an error to the screen.
                return render(
                    request,
                    "users/login.html",
                    {"error_message": "Incorrect username or password."},
                )
        else:
            # No post data availabe, let's just show the page to the user.
            return render(request, "users/login.html")
    else:
        return redirect("order:home")


def logout_user(request):
    logout(request)
    return redirect("user:login")


def user_register(request):

    if not request.user.is_authenticated:
        # if this is a POST request we need to process the form data
        template = "users/register.html"

        if request.method == "POST":
            # create a form instance and populate it with data from the request:
            form = RegisterForm(request.POST)
            # check whether it's valid:
            if form.is_valid():
                if User.objects.filter(username=form.cleaned_data["username"]).exists():
                    return render(
                        request,
                        template,
                        {"form": form, "error_message": "Username already exists."},
                    )
                elif User.objects.filter(email=form.cleaned_data["email"]).exists():
                    return render(
                        request,
                        template,
                        {"form": form, "error_message": "Email already exists."},
                    )
                elif form.cleaned_data["password"] != form.cleaned_data["password_repeat"]:
                    return render(
                        request,
                        template,
                        {"form": form, "error_message": "Passwords do not match."},
                    )
                else:
                    # Create the user:
                    user = User.objects.create_user(
                        form.cleaned_data["username"],
                        form.cleaned_data["email"],
                        form.cleaned_data["password"],
                    )
                    user.save()

                    # Login the user
                    login(request, user)

                    # redirect to accounts page:
                    return redirect("user:profile")

        # No post data availabe, let's just show the page.
        else:
            form = RegisterForm()

        return render(request, template, {"form": form})
    else:
        return redirect("order:home")


def profile(request):
    return render(request, "users/profile.html")

smurfelite/templates/users/login.html
{% extends 'base.html' %} 
<!--prettier ignore-->
{% load static %}
<!--prettier ignore-->
{% block css_link %}
<link rel="stylesheet" type="text/css" href="{% static '/css/login.css' %}" />
{% endblock css_link %}
<!--prettier ignore-->
{% block title %}Smurf Elite - Login{% endblock title %}
<!--prettier ignore-->
{% block body %}
<!-- LOGIN PAGE -->
<div class="login">
  <img src="{% static 'images/login.jpg' %}" alt="" />
</div>
<section class="vh-100">
  <div class="container-fluid h-custom">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-md-9 col-lg-6 col-xl-5 pt-5"></div>
      <div class="pt-5 col-md-8 col-lg-6 col-xl-4 offset-xl-1 text-white">
        <form action="{% url 'user:login' %}" method="POST">
          {% csrf_token %}
          <div
            class="d-flex flex-row align-items-center justify-content-center justify-content-lg-start"
          >
            <p class="lead fw-normal mb-0 me-3">Sign in with</p>
            <button type="button" class="btn btn-secondary btn-floating mx-1">
              <i class="fab fa-facebook-f"></i>
            </button>

            <button type="button" class="btn btn-secondary btn-floating mx-1">
              <i class="fab fa-google"></i>
            </button>

            <button type="button" class="btn btn-secondary btn-floating mx-1">
              <i class="fab fa-steam"></i>
            </button>
          </div>

          <div class="divider d-flex align-items-center my-4">
            <p class="text-center fw-bold mx-3 mb-0">Or</p>
          </div>

          <!-- Username input -->
          <div class="form-outline mb-4">
            <input
              type="text"
              id="username"
              name="username"
              class="form-control form-control-lg"
              placeholder="Enter a valid Username"
            />
            <label class="form-label" for="username">Username</label>
          </div>

          <!-- Password input -->
          <div class="form-outline mb-3">
            <input
              type="password"
              id="password"
              name="password"
              class="form-control form-control-lg"
              placeholder="Enter password"
            />
            <label class="form-label" for="password">Password</label>
          </div>

          <div class="d-flex justify-content-between align-items-center">
            <!-- Checkbox -->
            <div class="form-check mb-0">
              <input
                class="form-check-input me-2"
                type="checkbox"
                value=""
                id="form2Example3"
              />
              <label class="form-check-label" for="form2Example3">
                Remember me
              </label>
            </div>
            <a href="#!" class="link-dark">Forgot password?</a>
          </div>

          <div class="text-center text-lg-start mt-4 pt-2">
            <button
              type="submit"
              name="login"
              class="btn btn-secondary btn-lg"
              name="login"
              style="padding-left: 2.5rem; padding-right: 2.5rem"
            >
              Login
            </button>
            <p class="small fw-bold mt-2 pt-1 mb-0">
              Don't have an account? <a href="{% url 'user:register' %}" class="link-dark">Register</a>
            </p>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>
<!--prettier ignore-->
{% endblock body %}
<!--prettier ignore-->

smurfelite/templates/users/profile.html
{% extends 'base.html' %}
<!--prettier ignore-->
{% load static %}
<!--prettier ignore-->
{% block css_link %}
<link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}" />
{% endblock css_link %}
<!--prettier ignore-->
{% block title %}Smurf Elite - Home{% endblock title %}
<!--prettier ignore-->
{% block body %}
<!-- Carousal Images -->
<div
  id="carouselExampleFade"
  class="carousel slide carousel-fade carousal-custom"
  data-bs-ride="carousel"
>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img
        src="{% static 'images/csgo.jpg' %}"
        class="home-image d-block w-100"
        alt="csgo"
        height="700px"
      />
    </div>
    <div class="carousel-item">
      <img
        src="{% static 'images/valorant.png' %}"
        class="home-image d-block w-100"
        alt="valorant"
        height="700px"
      />
    </div>
    <div class="carousel-item">
      <img
        src="{% static 'images/gtav.jpg' %}"
        class="home-image d-block w-100"
        alt="gtav"
        height="700px"
      />
    </div>
  </div>
  <button
    class="carousel-control-prev"
    type="button"
    data-bs-target="#carouselExampleFade"
    data-bs-slide="prev"
  >
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button
    class="carousel-control-next"
    type="button"
    data-bs-target="#carouselExampleFade"
    data-bs-slide="next"
  >
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
<!-- ---------------------- -->
<!-- ---------------------- -->
<!-- Featured Games -->
<!-- ---------------------- -->
<!-- ---------------------- -->

<div class="row featured-games">
  <h1 class="page-title">Featured Games</h1>
  <div class="col-12 m-auto">
    <div class="owl-carousel owl-theme">
      <div class="item mb-4">
        <div class="card border-0 shadow">
          <img
            src="{% static 'images/csgo.jpg' %}"
            alt=""
            class="card-img-top"
          />
          <div class="card-body">
            <div class="card-title text-center">
              <h4>CSGO</h4>
            </div>
          </div>
        </div>
      </div>
      <div class="item">
        <div class="card border-0 shadow">
          <img
            src="{% static 'images/gtav.jpg' %}"
            alt=""
            class="card-img-top"
          />
          <div class="card-body">
            <div class="card-title text-center">
              <h4>Valorant</h4>
            </div>
          </div>
        </div>
      </div>
      <div class="item">
        <div class="card border-0 shadow">
          <img
            src="{% static 'images/valorant.png' %}"
            alt=""
            class="card-img-top"
          />
          <div class="card-body">
            <div class="card-title text-center">
              <h4>GTA V</h4>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- ---------------------- -->
<!-- ---------------------- -->
<!-- FAQs HTML -->
<!-- ---------------------- -->
<!-- ---------------------- -->
<div class="container-lg-12" style="padding: 0px 0px 0px 45px">
  <div class="row">
    <div class="col-md-12">
      <h1 class="page-title">Frequenlty Asked Questions (FAQs)</h1>
      <div
        class="accordion col-md-12"
        id="accordionExample"
      >
        <div class="card">
          <div class="card-header" id="headingOne">
            <h2 class="clearfix mb-0">
              <a
                class="btn btn-link"
                data-bs-toggle="collapse"
                data-bs-target="#collapseOne"
                aria-expanded="false"
                aria-controls="collapseOne"
                ><i class="fa fa-chevron-circle-down"></i>Why Choose
                Smurf Elite?</a
              >
            </h2>
          </div>
          <div
            id="collapseOne"
            class="collapse"
            aria-labelledby="headingOne"
            data-parent="#accordionExample"
          >
            <div class="card-body">
              <ul>
                <li>
                  Our goal is to satisfy our customers’ expectations. We strive
                  to provide you with the highest quality products. Customer
                  Satisfaction guaranteed!
                </li>
                <li>
                  We assure you that you get the best experience and you’ll
                  definitely continue shopping with us!
                </li>
                <li>
                  Check out our price ranges and decide your comfortable pick!
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="card">
          <div class="card-header" id="headingTwo">
            <h2 class="mb-0">
              <a
                class="btn btn-link collapsed"
                data-bs-toggle="collapse"
                data-bs-target="#collapseTwo"
                aria-expanded="false"
                aria-controls="collapseTwo"
                ><i class="fa fa-chevron-circle-down"></i>Can I trust
                Smurf Elite?</a
              >
            </h2>
          </div>
          <div
            id="collapseTwo"
            class="collapse"
            aria-labelledby="headingTwo"
            data-parent="#accordionExample"
          >
            <div class="card-body">
              <ul>
                <li>
                  Our biggest victory would be gaining your trust. Our
                  best-in-class service and products will definitely gain your
                  trust!
                </li>
                <li>
                  We provide excellent customer support and best in class
                  products
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="card">
          <div class="card-header" id="headingThree">
            <h2 class="mb-0">
              <a
                class="btn btn-link collapsed"
                data-bs-toggle="collapse"
                data-bs-target="#collapseThree"
                aria-expanded="false"
                aria-controls="collapseThree"
                ><i class="fa fa-chevron-circle-down"></i>What other accounts do
                you sell?</a
              >
            </h2>
          </div>
          <div
            id="collapseThree"
            class="collapse"
            aria-labelledby="headingThree"
            data-parent="#accordionExample"
          >
            <div class="card-body">
              We sell * CSGO, * GTA V, and * Valorant Accounts at the moment. Do
              check them out.
            </div>
          </div>
        </div>
        <div class="card">
          <div class="card-header" id="headingFour">
            <h2 class="mb-0">
              <a
                class="btn btn-link collapsed"
                data-bs-toggle="collapse"
                data-bs-target="#collapseFour"
                aria-expanded="false"
                aria-controls="collapseFour"
                ><i class="fa fa-chevron-circle-down"></i>What are the
                Benefits?</a
              >
            </h2>
          </div>
          <div
            id="collapseFour"
            class="collapse"
            aria-labelledby="headingFour"
            data-parent="#accordionExample"
          >
            <div class="card-body">
              Our UI, Active Customer Support, and Lightning-fast delivery are
              noteworthy and we provide offers frequently!
            </div>
          </div>
        </div>
        <div class="card">
          <div class="card-header" id="headingFour">
            <h2 class="mb-0">
              <a
                class="btn btn-link collapsed"
                data-bs-toggle="collapse"
                data-bs-target="#collapseFive"
                aria-expanded="false"
                aria-controls="collapseFive"
                ><i class="fa fa-chevron-circle-down"></i>How will I get my
                products?</a
              >
            </h2>
          </div>
          <div
            id="collapseFive"
            class="collapse"
            aria-labelledby="headingFour"
            data-parent="#accordionExample"
          >
            <div class="card-body">
              The ordered accounts will be delivered to you by the given Email
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="p-5"></div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<script
  src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"
  integrity="sha512-bPs7Ae6pVvhOSiIcyUClR7/q2OAsRiovw4vAkX+zJbw3ShAeeqezq50RIIcIURq7Oa20rW2n2q+fyXBNcU9lrw=="
  crossorigin="anonymous"
></script>
<script>
  $(".owl-carousel").owlCarousel({
    loop: true,
    margin: 15,
    nav: true,
    responsive: {
      0: {
        items: 1,
      },
      600: {
        items: 2,
      },
      1000: {
        items: 3,
      },
    },
  });
</script>
<!--prettier ignore-->
{% endblock body %}
<!--prettier ignore-->

smurfelite/templates/users/register.html
{% extends 'base.html' %}
<!--prettier ignore-->
{% load static %}
<!--prettier ignore-->
{% block css_link %}
<link rel="stylesheet" type="text/css" href="{% static '/css/login.css' %}" />
{% endblock css_link %}
<!--prettier ignore-->
{% block title %}Smurf Elite - Reigster{% endblock title %}
<!--prettier ignore-->
{% block body %}
<!-- LOGIN PAGE -->
<div class="login">
  <img src="{% static 'images/login.jpg' %}" alt="" />
</div>
<section class="vh-100">
  <div class="container-fluid h-custom">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-md-9 col-lg-6 col-xl-5 pt-5">
        <!-- <img src=""
              class="img-fluid" alt="Sample image"> -->
      </div>
      <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1 text-white">
        <form action="{% url 'user:register' %}" method="POST">
          {% csrf_token %}
          <div
            class="d-flex flex-row align-items-center justify-content-center justify-content-lg-start"
          >
            <p class="lead fw-normal mb-0 me-3">Sign up with</p>
            <button type="button" class="btn btn-secondary btn-floating mx-1">
              <i class="fab fa-facebook-f"></i>
            </button>

            <button type="button" class="btn btn-secondary btn-floating mx-1">
              <i class="fab fa-google"></i>
            </button>

            <button type="button" class="btn btn-secondary btn-floating mx-1">
              <i class="fab fa-steam"></i>
            </button>
          </div>

          <div class="divider d-flex align-items-center my-4">
            <p class="text-center fw-bold mx-3 mb-0">Or</p>
          </div>

          <!-- Email input -->
          <div class="form-outline mb-2">
            {{ form.email }}
            <label class="form-label" for="{{ form.email.id_for_label }}"
              >Email address</label
            >
          </div>

          <!-- Username input -->
          <div class="form-outline mb-2">
            {{ form.username }}
            <label class="form-label" for="{{ form.username.id_for_label }}">Username</label>
          </div>

          <!-- Password input -->
          <div class="form-outline mb-2">
            {{ form.password }}
            <label class="form-label" for="{{ form.paswword.id_for_label }}">Password</label>
          </div>

          <!-- Re-Password input -->
          <div class="form-outline mb-2">
            {{ form.password_repeat }}
            <label class="form-label" for="{{ form.password_repeat.id_for_label }}">Password</label>
          </div>

          <div class="d-flex justify-content-between align-items-center">
            <!-- Checkbox -->
            <div class="form-check mb-0">
              <input
                class="form-check-input me-2"
                type="checkbox"
                value=""
                id="form2Example3"
              />
              <label class="form-check-label" for="form2Example3">
                Remember me
              </label>
            </div>
          </div>

          <div class="text-center text-lg-start mt-2">
            <button
              type="submit"
              class="btn btn-secondary btn-lg"
              style="padding-left: 2.5rem; padding-right: 2.5rem"
            >
              Sign Up
            </button>
            <p class="small fw-bold m-2 pt-1 mb-0">
              Already have an account?
              <a href="#!" class="link-dark">Sign In</a>
            </p>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock body %}