smurfelite/games/urls.py
from django.urls import path

from . import views


urlpatterns = [

]

smurfelite/orders/urls.py
from django.urls import path

from . import views

app_name = 'order'

urlpatterns = [
    path('', views.home, name='home'),
    path('orders/cart/', views.cart, name='cart'),
    path('orders/checkout/', views.checkout, name='checkout'),
]

smurfelite/smurfelite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("users.urls")),
    path('', include("orders.urls")),
    path('games/', include("games.urls")),
]

smurfelite/users/urls.py
from django.urls import path

from . import views
app_name = 'user'

urlpatterns = [
    path("login/", views.user_login, name="login"),
    path('logout/', views.logout_user, name='logout'),
    path("register/", views.user_register, name="register"),
    path("profile/", views.profile, name="profile"),
]

smurfelite/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css"
      integrity="sha512-tS3S5qG0BlhnQROyJXvNjeEM4UpMXHrQfTGmbQ1gKmelCxlSEBUaxhRBj/EFTzpbP4RVSrpEikbmdJobCvhE3g=="
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css"
      integrity="sha512-sMXtMNL1zRzolHYKEujM2AqCLUR9F2C4/05cdbxjjLSRvMQIciEPCQZo++nk7go3BtSuK9kfa/s+a4f4i5pLkw=="
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
      integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static '/css/base.css' %}"
    />
    {% block css_link %} {% endblock css_link %}
    <!--Jquery-->
    <script type="text/javascript" src="js/JQuery3.3.1.js"></script>
    <script type="text/javascript" src="js/lightslider.js"></script>
    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% block navbar %}

    <!-- NAVBAR -->
    <nav class="navbar fixed-top navbar-expand-md nav-bg shadow-5-strong">
      <a href="{% url 'order:home' %}" class="navbar-brand fs-3 m-3 text-white"
        ><img
          src="{% static 'images/Smurfelite.png' %}"
          alt="logo"
          class="logo"
          width="115px"
      /></a>
      <button
        class="navbar-toggler me-3 text-white"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#btn"
      >
        <span class="navbar-toggler-icon">
          <i class="fas fa-solid fa-bars"></i>
        </span>
      </button>
      <div class="collapse navbar-collapse" id="btn">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a href="#" class="nav-link mx-2 text-white fs-5">Home</a>
          </li>
          <li class="nav-item dropdown">
            <a
              class="nav-link mx-2 text-white fs-5"
              href="#"
              role="button"
              data-bs-toggle="dropdown"
              aria-expanded="false"
            >
              Games
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#">CSGO</a></li>
              <li><a class="dropdown-item" href="#">Valorant</a></li>
              <li><a class="dropdown-item" href="#">GTA V</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link mx-3 text-white fs-5" title="cart"
              ><i class="fas fa-cart-shopping"></i
            ></a>
          </li>
          <li class="nav-item">
            {% if user.is_authenticated %}
              <a href="{% url 'user:profile' %}" class="nav-link mx-3 text-white fs-5" title="Proflie">
            {% else %}
            <a href="{% url 'user:login' %}" class="nav-link mx-3 text-white fs-5" title="Login">
            {% endif %}
            <i class="fas fa-user"></i
            ></a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'user:logout' %}" class="nav-link mx-3 text-white fs-5"
              ><i class="fas fa-door-open"></i></i
            ></a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a href="#" class="nav-link mx-3 text-white fs-5" title="Logout"></a>
          </li>
        </ul>
      </div>
    </nav>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->

    {% endblock navbar %}
    <div class="central_body">{% block body %}{% endblock body %}</div>
    {% block footer %}
    <footer>
      <div class="row-footer primary-footer">
        <div class="column-footer about">
          <h3 class="footer-h3">Smurf Elite</h3>

          <p>One place to buy all gaming accounts.</p>

          <div class="social-footer">
            <i class="fa-brands fa-facebook"></i>
            <i class="fa-brands fa-instagram"></i>
            <i class="fa-brands fa-twitter"></i>
            <i class="fa-brands fa-discord"></i>
          </div>
        </div>

        <div class="column-footer links-footer">
          <h3 class="footer-h3">Site</h3>

          <ul class="footer-ul">
            <li>
              <a href="#faq">Home</a>
            </li>
            <li>
              <a href="#cookies-policy">Games</a>
            </li>
            <li>
              <a href="#terms-of-services">Cart</a>
            </li>
            <li>
              <a href="#support">Support</a>
            </li>
          </ul>
        </div>

        <div class="column-footer links-footer">
          <h3 class="footer-h3">Games</h3>
          <ul class="footer-ul">
            <li>
              <a href="#faq">CSGO</a>
            </li>
            <li>
              <a href="#cookies-policy">Valorant</a>
            </li>
            <li>
              <a href="#terms-of-services">GTA V</a>
            </li>
          </ul>
        </div>

        <div class="column-footer subscribe">
          <h3 class="footer-h3">Review Us on</h3>
          <div>
            <img
              class="footer-img"
              src="{% static 'images/trustpilot.png'%}"
              alt="trust_pilot"
            />
          </div>
        </div>
      </div>

      <div class="row-footer copyright">
        <p>Copyright &copy; 2022 Smurf Elite</p>
      </div>
    </footer>
    {% endblock footer %}
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
    <!-- Nav bar transaperent script -->
    <script>
      var nav = document.querySelector("nav");

      window.addEventListener("scroll", function () {
        if (window.pageYOffset > 100) {
          nav.classList.add("bg-dark", "shadow");
        } else {
          nav.classList.remove("bg-dark", "shadow");
        }
      });
    </script>
  </body>
</html>